server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/user_servicedb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Muskaan@8756

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

